[[constraint]]
  name = "github.com/tendermint/tmlibs"
  version = "0.8.2"

[[constraint]]
  name = "github.com/tendermint/go-crypto"
  version = "0.6.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "0.8.0-rc0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true