[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "0.22.8"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "0.9.2"
  
[prune]
  go-tests = true
  unused-packages = true
