[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.5.4"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "v0.12.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "v0.28.1"

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "b001fa50d6b27f3f0bb175a87d0cb55426d0a0ae"

[prune]
  go-tests = true
  unused-packages = true