[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "=v0.11.1"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "v0.26.4"

[prune]
  go-tests = true
  unused-packages = true