[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "v0.30.2"

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "3a907f965fc16db5f7787e18d4434bbe46d47f6e"

[prune]
  go-tests = true
  unused-packages = true