version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ndidplatform/smart-contract
    steps:
      - checkout
      - run:
          name: Install Tendermint 0.19.5
          command: |
            mkdir -p /go/src/github.com/tendermint
            cd /go/src/github.com/tendermint
            git clone https://github.com/tendermint/tendermint.git
            cd tendermint
            git checkout v0.19.5
            make get_tools
            make get_vendor_deps
            make install

      - run:
          name: Setup Smartcontract
          command: |
            go get github.com/tendermint/tmlibs/common
            cd abci
            dep ensure
  
      - run:
          name: Start ABCI
          command: |
            DB_NAME=IdP_DB go run abci/server.go tcp://127.0.0.1:46000
          background: true

      - run:
          name: Start Tendermint
          command: |
            tendermint --home ./config/tendermint/IdP unsafe_reset_all && tendermint --home ./config/tendermint/IdP node --consensus.create_empty_blocks=false
          background: true

      - run: sleep 15
      - run:
          name: Test ABCI
          command: |
            TENDERMINT_ADDRESS=http://localhost:45000 go test -v

  push_to_docker_hub:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build docker images
          command: |
            cd docker
            ./build.sh
      - run:
          name: Push to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push bomubomu/abci:latest
            docker push bomubomu/tendermint:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - push_to_docker_hub:
          requires:
            - build
