version: '3.3'
services:
  tendermint:
    build: 
      context: ../
      dockerfile: docker/Dockerfile-tendermint
      labels:
        build.commit: ${BUILD_COMMIT}
        build.date: ${BUILD_DATE}
    image: bomubomu/tendermint:latest
  abci:
    build:
      context: ../
      dockerfile: docker/Dockerfile-abci
      labels:
        build.commit: ${BUILD_COMMIT}
        build.date: ${BUILD_DATE}
    image: bomubomu/abci:latest
